# Generated by Django 2.2.19 on 2022-11-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0005_auto_20221106_1755'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_user_author'),
        ),
    ]
